defaults:
  - model: Llama-3.2-3B-Instruct
  - trainer: GradAscent
  - data: unlearn
  - collator: DataCollatorForSupervisedDataset
  - eval: tofu
  - hydra: default
  - paths: default
  - experiment: null
  - _self_

# <-- NEW: expose a root-level 'mode' so hydra.run.dir can interpolate it
mode: ${trainer.mode}

trainer:
  args:
    remove_unused_columns: False
  mode: unlearn
  task_name: ???

  # ---- Epoch-wise reparameterization (OFF by default) ----
  reparam:
    enable: false           # set true (or override from CLI) to turn on
    ops: [attn, mlp]
    seed_offset: 0
    reset_optimizer_each_epoch: false
    set_epoch_on_dataset: true
